### ISSUE TITLE
dsd file

### ISSUE THREAD

**Issue by reni99** [csarven/transparency-linked-data#2]
You told me to crate the dsd file for the CPI2102. So I looked at the meta.ttl file in the data folder of the master branch. So is it the aim to extend this meta.ttl file for the CPI2012 or create a new one?

Second question:
I see, that it says which URI represent what (with comments and properties). But I can't see the final propose of the file. Can you explain me what this file finally serves for?

**Comment by csarven** [comment]
1. Extended as meta.ttl contains DSDs for CPI2009-CPI2011. Update meta.ttl with the CPI2012 DSD in CPI2012 branch. When the CPI2012 is healthy, it will be merged with master.
2. The DSD describes the shape of the dataset i.e., the observations, as well as what and how classifications are used. See http://www.w3.org/TR/vocab-data-cube/#dsd
